[2024-12-23T14:02:36.868+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T14:02:36.894+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_spark_cluster.spark_action manual__2024-12-23T14:02:35.318160+00:00 [queued]>
[2024-12-23T14:02:36.906+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_spark_cluster.spark_action manual__2024-12-23T14:02:35.318160+00:00 [queued]>
[2024-12-23T14:02:36.906+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-23T14:02:36.919+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): spark_action> on 2024-12-23 14:02:35.318160+00:00
[2024-12-23T14:02:36.937+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2979) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T14:02:36.953+0000] {standard_task_runner.py:72} INFO - Started process 2982 to run task
[2024-12-23T14:02:36.952+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_spark_cluster', 'spark_action', 'manual__2024-12-23T14:02:35.318160+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/dag_calendar.py', '--cfg-path', '/tmp/tmpcuidgpdp']
[2024-12-23T14:02:36.957+0000] {standard_task_runner.py:105} INFO - Job 247: Subtask spark_action
[2024-12-23T14:02:37.068+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_spark_cluster.spark_action manual__2024-12-23T14:02:35.318160+00:00 [running]> on host 85f5ad808200
[2024-12-23T14:02:37.310+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_spark_cluster' AIRFLOW_CTX_TASK_ID='spark_action' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T14:02:35.318160+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T14:02:35.318160+00:00'
[2024-12-23T14:02:37.319+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T14:02:37.536+0000] {logging_mixin.py:190} INFO - Error starting Spark Master: 409 Client Error for http+docker://localhost/v1.47/containers/create?name=spark-master: Conflict ("Conflict. The container name "/spark-master" is already in use by container "b99de38db9197063af74f51a2aaf99c7c27e32001f480a94aae5b0beb34d31ce". You have to remove (or rename) that container to be able to reuse that name.")
[2024-12-23T14:02:38.063+0000] {logging_mixin.py:190} INFO - Error starting Spark Worker: 500 Server Error for http+docker://localhost/v1.47/containers/87fa2bb46275b4a229af343989c7011c9974d62ef88cac82d22ac1a72fb9f798/start: Internal Server Error ("driver failed programming external connectivity on endpoint spark-worker (0a399a273fe6f24e4526b7f98f8dad3019b5e01fc4cfda672e7f91fe17b029e2): Bind for 0.0.0.0:8081 failed: port is already allocated")
[2024-12-23T14:02:38.073+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-23T14:02:38.237+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T14:02:38.239+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_spark_cluster, task_id=spark_action, run_id=manual__2024-12-23T14:02:35.318160+00:00, execution_date=20241223T140235, start_date=20241223T140236, end_date=20241223T140238
[2024-12-23T14:02:38.357+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-23T14:02:38.471+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T14:02:38.473+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
