[2024-12-27T15:34:29.183+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:34:29.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/kafka_streaming.py for tasks to queue
[2024-12-27T15:34:29.191+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:34:29.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:34:29.210+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:34:29.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/kafka_streaming.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_streaming.py", line 48, in <module>
    get_data()
  File "/opt/airflow/dags/kafka_streaming.py", line 11, in get_data
    with open('airflow_testing/config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow_testing/config.json'
[2024-12-27T15:34:29.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:34:29.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/kafka_streaming.py took 0.118 seconds
[2024-12-27T15:34:59.924+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:34:59.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/kafka_streaming.py for tasks to queue
[2024-12-27T15:34:59.933+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:34:59.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:34:59.946+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:34:59.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/kafka_streaming.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_streaming.py", line 48, in <module>
    get_data()
  File "/opt/airflow/dags/kafka_streaming.py", line 11, in get_data
    with open('airflow_testing/config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow_testing/config.json'
[2024-12-27T15:34:59.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:34:59.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/kafka_streaming.py took 0.071 seconds
[2024-12-27T15:35:30.592+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:35:30.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/kafka_streaming.py for tasks to queue
[2024-12-27T15:35:30.641+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:35:30.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:35:30.659+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:35:30.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/kafka_streaming.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_streaming.py", line 48, in <module>
    get_data()
  File "/opt/airflow/dags/kafka_streaming.py", line 11, in get_data
    with open('airflow_testing/config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow_testing/config.json'
[2024-12-27T15:35:30.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:35:30.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/kafka_streaming.py took 0.297 seconds
[2024-12-27T15:36:02.319+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:36:02.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/kafka_streaming.py for tasks to queue
[2024-12-27T15:36:02.410+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:36:02.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:36:02.506+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:36:02.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/kafka_streaming.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_streaming.py", line 48, in <module>
    get_data()
  File "/opt/airflow/dags/kafka_streaming.py", line 11, in get_data
    with open('airflow_testing/config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow_testing/config.json'
[2024-12-27T15:36:02.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:36:02.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/kafka_streaming.py took 0.576 seconds
[2024-12-27T15:36:34.347+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:36:34.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/kafka_streaming.py for tasks to queue
[2024-12-27T15:36:34.373+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:36:34.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:36:34.490+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:36:34.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/kafka_streaming.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_streaming.py", line 48, in <module>
    get_data()
  File "/opt/airflow/dags/kafka_streaming.py", line 11, in get_data
    with open('airflow_testing/config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow_testing/config.json'
[2024-12-27T15:36:34.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:36:35.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/kafka_streaming.py took 0.785 seconds
[2024-12-27T15:37:05.988+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:37:06.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/kafka_streaming.py for tasks to queue
[2024-12-27T15:37:06.046+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:37:06.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:37:06.215+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:37:06.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/kafka_streaming.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_streaming.py", line 48, in <module>
    get_data()
  File "/opt/airflow/dags/kafka_streaming.py", line 11, in get_data
    with open('airflow_testing/config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow_testing/config.json'
[2024-12-27T15:37:06.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:37:06.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/kafka_streaming.py took 0.709 seconds
[2024-12-27T15:37:37.155+0000] {processor.py:186} INFO - Started process (PID=161) to work on /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:37:37.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/kafka_streaming.py for tasks to queue
[2024-12-27T15:37:37.192+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:37:37.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:37:37.214+0000] {logging_mixin.py:190} INFO - [2024-12-27T15:37:37.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/kafka_streaming.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_streaming.py", line 48, in <module>
    get_data()
  File "/opt/airflow/dags/kafka_streaming.py", line 11, in get_data
    with open('airflow_testing/config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow_testing/config.json'
[2024-12-27T15:37:37.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_streaming.py
[2024-12-27T15:37:37.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/kafka_streaming.py took 0.212 seconds
