[2025-01-05T13:52:54.461+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T13:52:54.599+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_Category_NTBK.NB_Notebook_job scheduled__2025-01-03T15:30:00+00:00 [queued]>
[2025-01-05T13:52:54.722+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_Category_NTBK.NB_Notebook_job scheduled__2025-01-03T15:30:00+00:00 [queued]>
[2025-01-05T13:52:54.727+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T13:52:54.859+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): NB_Notebook_job> on 2025-01-03 15:30:00+00:00
[2025-01-05T13:52:54.964+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T13:52:55.003+0000] {standard_task_runner.py:72} INFO - Started process 112 to run task
[2025-01-05T13:52:55.029+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_Category_NTBK', 'NB_Notebook_job', 'scheduled__2025-01-03T15:30:00+00:00', '--job-id', '562', '--raw', '--subdir', 'DAGS_FOLDER/dag_category.py', '--cfg-path', '/tmp/tmpy45v_vtv']
[2025-01-05T13:52:55.046+0000] {standard_task_runner.py:105} INFO - Job 562: Subtask NB_Notebook_job
[2025-01-05T13:52:55.748+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_Category_NTBK.NB_Notebook_job scheduled__2025-01-03T15:30:00+00:00 [running]> on host 44275986e897
[2025-01-05T13:52:56.258+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anoop M' AIRFLOW_CTX_DAG_ID='dag_Category_NTBK' AIRFLOW_CTX_TASK_ID='NB_Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T15:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-03T15:30:00+00:00'
[2025-01-05T13:52:56.267+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T13:52:58.383+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2025-01-05T13:53:06.757+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_DIM_Category.ipynb
[2025-01-05T13:53:06.778+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output/NB_DIM_Category.ipynb
[2025-01-05T13:53:13.733+0000] {docker.py:73} INFO - Executing notebook with kernel: python3
[2025-01-05T13:53:13.764+0000] {docker.py:73} INFO - Executing Cell 1---------------------------------------
[2025-01-05T13:53:22.683+0000] {docker.py:73} INFO - Ending Cell 1------------------------------------------
[2025-01-05T13:53:22.766+0000] {docker.py:73} INFO - Executing Cell 2---------------------------------------
[2025-01-05T13:53:23.156+0000] {docker.py:73} INFO - Ending Cell 2------------------------------------------
[2025-01-05T13:53:23.251+0000] {docker.py:73} INFO - Executing Cell 3---------------------------------------
[2025-01-05T13:54:01.926+0000] {docker.py:73} INFO - :: loading settings :: url = jar:file:/usr/local/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-01-05T13:54:07.543+0000] {docker.py:73} INFO - Ivy Default Cache set to: /home/jovyan/.ivy2/cache
[2025-01-05T13:54:07.605+0000] {docker.py:73} INFO - The jars for the packages stored in: /home/jovyan/.ivy2/jars
[2025-01-05T13:54:07.841+0000] {docker.py:73} INFO - io.delta#delta-spark_2.12 added as a dependency
[2025-01-05T13:54:07.907+0000] {docker.py:73} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-067fc2fd-8d62-4df7-bf86-06a595b71069;1.0
[2025-01-05T13:54:07.952+0000] {docker.py:73} INFO - 	confs: [default]
[2025-01-05T13:54:28.354+0000] {docker.py:73} INFO - 	found io.delta#delta-spark_2.12;3.1.0 in central
[2025-01-05T13:54:28.719+0000] {docker.py:73} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar ...
[2025-01-05T13:57:19.187+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-05T13:57:19.205+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-05T13:57:19.215+0000] {process_utils.py:132} INFO - Sending 15 to group 112. PIDs of all processes in the group: [112]
[2025-01-05T13:57:19.221+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 112
[2025-01-05T13:57:19.231+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-05T13:57:19.251+0000] {docker.py:539} INFO - Stopping docker container
[2025-01-05T13:57:19.933+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T13:57:19.998+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=112, status='terminated', exitcode=0, started='13:52:54') (112) terminated with exit code 0
