[2024-12-24T10:51:12.051+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-24T10:51:12.073+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_Calendar_NTBK.run_papermill_notebook manual__2024-12-24T10:51:07.310152+00:00 [queued]>
[2024-12-24T10:51:12.082+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_Calendar_NTBK.run_papermill_notebook manual__2024-12-24T10:51:07.310152+00:00 [queued]>
[2024-12-24T10:51:12.082+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-24T10:51:12.102+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_papermill_notebook> on 2024-12-24 10:51:07.310152+00:00
[2024-12-24T10:51:12.111+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1343) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-24T10:51:12.113+0000] {standard_task_runner.py:72} INFO - Started process 1346 to run task
[2024-12-24T10:51:12.114+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_Calendar_NTBK', 'run_papermill_notebook', 'manual__2024-12-24T10:51:07.310152+00:00', '--job-id', '436', '--raw', '--subdir', 'DAGS_FOLDER/dag_calendar.py', '--cfg-path', '/tmp/tmprbg9d6om']
[2024-12-24T10:51:12.116+0000] {standard_task_runner.py:105} INFO - Job 436: Subtask run_papermill_notebook
[2024-12-24T10:51:12.194+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_Calendar_NTBK.run_papermill_notebook manual__2024-12-24T10:51:07.310152+00:00 [running]> on host ca7403376fcd
[2024-12-24T10:51:12.278+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_Calendar_NTBK' AIRFLOW_CTX_TASK_ID='run_papermill_notebook' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T10:51:07.310152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T10:51:07.310152+00:00'
[2024-12-24T10:51:12.282+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-24T10:51:12.289+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-24T10:51:12.295+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'papermill /home/jovyan/Notebooks/NB_Calendar.ipynb /home/jovyan/Notebooks/output/NB_Calendar.ipynb --log-output -p spark_master spark://spark-master:7077']
[2024-12-24T10:51:12.307+0000] {subprocess.py:99} INFO - Output:
[2024-12-24T10:51:12.316+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: papermill: command not found
[2024-12-24T10:51:12.317+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2024-12-24T10:51:12.337+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-24T10:51:12.344+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_Calendar_NTBK, task_id=run_papermill_notebook, run_id=manual__2024-12-24T10:51:07.310152+00:00, execution_date=20241224T105107, start_date=20241224T105112, end_date=20241224T105112
[2024-12-24T10:51:12.357+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-24T10:51:12.358+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 436 for task run_papermill_notebook (Bash command failed. The command returned a non-zero exit code 127.; 1346)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-24T10:51:12.383+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-24T10:51:12.412+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-24T10:51:12.413+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
