[2024-12-24T18:06:50.611+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-24T18:06:50.622+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_Calendar_NTBK.NB_Notebook_job manual__2024-12-24T18:06:48.628500+00:00 [queued]>
[2024-12-24T18:06:50.627+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_Calendar_NTBK.NB_Notebook_job manual__2024-12-24T18:06:48.628500+00:00 [queued]>
[2024-12-24T18:06:50.628+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-24T18:06:50.635+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): NB_Notebook_job> on 2024-12-24 18:06:48.628500+00:00
[2024-12-24T18:06:50.640+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=657) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-24T18:06:50.642+0000] {standard_task_runner.py:72} INFO - Started process 659 to run task
[2024-12-24T18:06:50.642+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_Calendar_NTBK', 'NB_Notebook_job', 'manual__2024-12-24T18:06:48.628500+00:00', '--job-id', '477', '--raw', '--subdir', 'DAGS_FOLDER/dag_calendar.py', '--cfg-path', '/tmp/tmp8_qgtnym']
[2024-12-24T18:06:50.643+0000] {standard_task_runner.py:105} INFO - Job 477: Subtask NB_Notebook_job
[2024-12-24T18:06:50.687+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_Calendar_NTBK.NB_Notebook_job manual__2024-12-24T18:06:48.628500+00:00 [running]> on host 68a5c0b3bbe6
[2024-12-24T18:06:50.744+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_Calendar_NTBK' AIRFLOW_CTX_TASK_ID='NB_Notebook_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T18:06:48.628500+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T18:06:48.628500+00:00'
[2024-12-24T18:06:50.746+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-24T18:06:50.928+0000] {docker.py:379} INFO - Starting docker container from image spark-cluster:version-1.0.0
[2024-12-24T18:06:54.009+0000] {docker.py:73} INFO - Input Notebook:  /home/jovyan/Notebooks/NB_Calendar.ipynb
[2024-12-24T18:06:54.015+0000] {docker.py:73} INFO - Output Notebook: /home/jovyan/Notebooks/output/NB_Calendar.ipynb
[2024-12-24T18:06:56.470+0000] {docker.py:73} INFO - Executing notebook with kernel: python3
[2024-12-24T18:06:56.475+0000] {docker.py:73} INFO - Executing Cell 1---------------------------------------
[2024-12-24T18:06:57.960+0000] {docker.py:73} INFO - Ending Cell 1------------------------------------------
[2024-12-24T18:06:57.982+0000] {docker.py:73} INFO - Executing Cell 2---------------------------------------
[2024-12-24T18:06:58.016+0000] {docker.py:73} INFO - Ending Cell 2------------------------------------------
[2024-12-24T18:06:58.024+0000] {docker.py:73} INFO - Executing Cell 3---------------------------------------
[2024-12-24T18:06:59.690+0000] {docker.py:73} INFO - :: loading settings :: url = jar:file:/usr/local/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-12-24T18:06:59.799+0000] {docker.py:73} INFO - Ivy Default Cache set to: /home/jovyan/.ivy2/cache
[2024-12-24T18:06:59.801+0000] {docker.py:73} INFO - The jars for the packages stored in: /home/jovyan/.ivy2/jars
[2024-12-24T18:06:59.807+0000] {docker.py:73} INFO - io.delta#delta-spark_2.12 added as a dependency
[2024-12-24T18:06:59.811+0000] {docker.py:73} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-65daf6ad-d7f5-447e-94b7-db40ad319fa4;1.0
[2024-12-24T18:06:59.813+0000] {docker.py:73} INFO - 	confs: [default]
[2024-12-24T18:07:16.178+0000] {docker.py:73} INFO - :: resolution report :: resolve 16369ms :: artifacts dl 0ms
[2024-12-24T18:07:16.183+0000] {docker.py:73} INFO - 	:: modules in use:
[2024-12-24T18:07:16.183+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-24T18:07:16.183+0000] {docker.py:73} INFO - 	|                  |            modules            ||   artifacts   |
[2024-12-24T18:07:16.184+0000] {docker.py:73} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-12-24T18:07:16.184+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-24T18:07:16.184+0000] {docker.py:73} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2024-12-24T18:07:16.184+0000] {docker.py:73} INFO - 	---------------------------------------------------------------------
[2024-12-24T18:07:16.186+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.186+0000] {docker.py:73} INFO - :: problems summary ::
[2024-12-24T18:07:16.187+0000] {docker.py:73} INFO - :::: WARNINGS
[2024-12-24T18:07:16.187+0000] {docker.py:73} INFO - 		module not found: io.delta#delta-spark_2.12;3.1.0
[2024-12-24T18:07:16.188+0000] {docker.py:73} INFO - 	==== local-m2-cache: tried
[2024-12-24T18:07:16.188+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.189+0000] {docker.py:73} INFO - 	  file:/home/jovyan/.m2/repository/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-24T18:07:16.189+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.190+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-24T18:07:16.191+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.191+0000] {docker.py:73} INFO - 	  file:/home/jovyan/.m2/repository/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-24T18:07:16.192+0000] {docker.py:73} INFO - 	==== local-ivy-cache: tried
[2024-12-24T18:07:16.192+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.193+0000] {docker.py:73} INFO - 	  /home/jovyan/.ivy2/local/io.delta/delta-spark_2.12/3.1.0/ivys/ivy.xml
[2024-12-24T18:07:16.193+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.194+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-24T18:07:16.194+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.195+0000] {docker.py:73} INFO - 	  /home/jovyan/.ivy2/local/io.delta/delta-spark_2.12/3.1.0/jars/delta-spark_2.12.jar
[2024-12-24T18:07:16.195+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.195+0000] {docker.py:73} INFO - 	==== central: tried
[2024-12-24T18:07:16.196+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.196+0000] {docker.py:73} INFO - 	  https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-24T18:07:16.196+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.196+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-24T18:07:16.196+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.197+0000] {docker.py:73} INFO - 	  https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-24T18:07:16.197+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.197+0000] {docker.py:73} INFO - 	==== spark-packages: tried
[2024-12-24T18:07:16.197+0000] {docker.py:73} INFO - 	  https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom
[2024-12-24T18:07:16.197+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.197+0000] {docker.py:73} INFO - 	  -- artifact io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar:
[2024-12-24T18:07:16.197+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.198+0000] {docker.py:73} INFO - 	  https://repos.spark-packages.org/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar
[2024-12-24T18:07:16.198+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.198+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-24T18:07:16.198+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.198+0000] {docker.py:73} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2024-12-24T18:07:16.198+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.198+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-24T18:07:16.199+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.199+0000] {docker.py:73} INFO - 		:: io.delta#delta-spark_2.12;3.1.0: not found
[2024-12-24T18:07:16.199+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.199+0000] {docker.py:73} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2024-12-24T18:07:16.199+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.199+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.200+0000] {docker.py:73} INFO - :::: ERRORS
[2024-12-24T18:07:16.200+0000] {docker.py:73} INFO - 	Server access error at url https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.pom (java.net.ConnectException: Connection refused)
[2024-12-24T18:07:16.200+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.200+0000] {docker.py:73} INFO - 	Server access error at url https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar (java.net.ConnectException: Connection refused)
[2024-12-24T18:07:16.200+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.201+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:16.201+0000] {docker.py:73} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-12-24T18:07:16.201+0000] {docker.py:73} INFO - Exception in thread "main"
[2024-12-24T18:07:16.201+0000] {docker.py:73} INFO - java.lang.RuntimeException: [unresolved dependency: io.delta#delta-spark_2.12;3.1.0: not found]
[2024-12-24T18:07:16.201+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1537)
[2024-12-24T18:07:16.202+0000] {docker.py:73} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2024-12-24T18:07:16.202+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
[2024-12-24T18:07:16.202+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2024-12-24T18:07:16.202+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-12-24T18:07:16.202+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-12-24T18:07:16.202+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-12-24T18:07:16.202+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-12-24T18:07:16.203+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-12-24T18:07:16.203+0000] {docker.py:73} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-12-24T18:07:16.601+0000] {docker.py:73} INFO - Ending Cell 3------------------------------------------
[2024-12-24T18:07:17.048+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2024-12-24T18:07:17.049+0000] {docker.py:73} INFO -   File "/opt/conda/bin/papermill", line 8, in <module>
[2024-12-24T18:07:17.050+0000] {docker.py:73} INFO -     sys.exit(papermill())
[2024-12-24T18:07:17.050+0000] {docker.py:73} INFO -              ^^^^^^^^^^^
[2024-12-24T18:07:17.051+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2024-12-24T18:07:17.051+0000] {docker.py:73} INFO -     return self.main(*args, **kwargs)
[2024-12-24T18:07:17.051+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:07:17.051+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2024-12-24T18:07:17.052+0000] {docker.py:73} INFO -     rv = self.invoke(ctx)
[2024-12-24T18:07:17.052+0000] {docker.py:73} INFO -          ^^^^^^^^^^^^^^^^
[2024-12-24T18:07:17.052+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2024-12-24T18:07:17.052+0000] {docker.py:73} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2024-12-24T18:07:17.056+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:07:17.060+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2024-12-24T18:07:17.060+0000] {docker.py:73} INFO -     return __callback(*args, **kwargs)
[2024-12-24T18:07:17.060+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:07:17.061+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2024-12-24T18:07:17.061+0000] {docker.py:73} INFO -     return f(get_current_context(), *args, **kwargs)
[2024-12-24T18:07:17.061+0000] {docker.py:73} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-24T18:07:17.061+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
[2024-12-24T18:07:17.061+0000] {docker.py:73} INFO -     execute_notebook(
[2024-12-24T18:07:17.061+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
[2024-12-24T18:07:17.062+0000] {docker.py:73} INFO -     raise_for_execution_errors(nb, output_path)
[2024-12-24T18:07:17.062+0000] {docker.py:73} INFO -   File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
[2024-12-24T18:07:17.062+0000] {docker.py:73} INFO -     raise error
[2024-12-24T18:07:17.062+0000] {docker.py:73} INFO - papermill.exceptions.PapermillExecutionError: 
[2024-12-24T18:07:17.062+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2024-12-24T18:07:17.062+0000] {docker.py:73} INFO - Exception encountered at "In [3]":
[2024-12-24T18:07:17.063+0000] {docker.py:73} INFO - ---------------------------------------------------------------------------
[2024-12-24T18:07:17.063+0000] {docker.py:73} INFO - PySparkRuntimeError                       Traceback (most recent call last)
[2024-12-24T18:07:17.063+0000] {docker.py:73} INFO - Cell In[3], line 2
[2024-12-24T18:07:17.063+0000] {docker.py:73} INFO -       1 # Configure Spark with Delta Lake (if needed)
[2024-12-24T18:07:17.063+0000] {docker.py:73} INFO - ----> 2 spark = configure_spark_with_delta_pip(builder).getOrCreate()
[2024-12-24T18:07:17.063+0000] {docker.py:73} INFO -       3 # Now you can use the Spark session
[2024-12-24T18:07:17.063+0000] {docker.py:73} INFO -       4 spark
[2024-12-24T18:07:17.064+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:17.064+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/sql/session.py:497, in SparkSession.Builder.getOrCreate(self)
[2024-12-24T18:07:17.064+0000] {docker.py:73} INFO -     495     sparkConf.set(key, value)
[2024-12-24T18:07:17.064+0000] {docker.py:73} INFO -     496 # This SparkContext may be an existing one.
[2024-12-24T18:07:17.064+0000] {docker.py:73} INFO - --> 497 sc = SparkContext.getOrCreate(sparkConf)
[2024-12-24T18:07:17.064+0000] {docker.py:73} INFO -     498 # Do not update `SparkConf` for existing `SparkContext`, as it's shared
[2024-12-24T18:07:17.064+0000] {docker.py:73} INFO -     499 # by all sessions.
[2024-12-24T18:07:17.064+0000] {docker.py:73} INFO -     500 session = SparkSession(sc, options=self._options)
[2024-12-24T18:07:17.065+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:17.065+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:515, in SparkContext.getOrCreate(cls, conf)
[2024-12-24T18:07:17.065+0000] {docker.py:73} INFO -     513 with SparkContext._lock:
[2024-12-24T18:07:17.065+0000] {docker.py:73} INFO -     514     if SparkContext._active_spark_context is None:
[2024-12-24T18:07:17.065+0000] {docker.py:73} INFO - --> 515         SparkContext(conf=conf or SparkConf())
[2024-12-24T18:07:17.065+0000] {docker.py:73} INFO -     516     assert SparkContext._active_spark_context is not None
[2024-12-24T18:07:17.066+0000] {docker.py:73} INFO -     517     return SparkContext._active_spark_context
[2024-12-24T18:07:17.066+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:17.066+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:201, in SparkContext.__init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls, udf_profiler_cls, memory_profiler_cls)
[2024-12-24T18:07:17.066+0000] {docker.py:73} INFO -     195 if gateway is not None and gateway.gateway_parameters.auth_token is None:
[2024-12-24T18:07:17.066+0000] {docker.py:73} INFO -     196     raise ValueError(
[2024-12-24T18:07:17.066+0000] {docker.py:73} INFO -     197         "You are trying to pass an insecure Py4j gateway to Spark. This"
[2024-12-24T18:07:17.067+0000] {docker.py:73} INFO -     198         " is not allowed as it is a security risk."
[2024-12-24T18:07:17.067+0000] {docker.py:73} INFO -     199     )
[2024-12-24T18:07:17.067+0000] {docker.py:73} INFO - --> 201 SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2024-12-24T18:07:17.067+0000] {docker.py:73} INFO -     202 try:
[2024-12-24T18:07:17.069+0000] {docker.py:73} INFO -     203     self._do_init(
[2024-12-24T18:07:17.069+0000] {docker.py:73} INFO -     204         master,
[2024-12-24T18:07:17.069+0000] {docker.py:73} INFO -     205         appName,
[2024-12-24T18:07:17.069+0000] {docker.py:73} INFO -    (...)
[2024-12-24T18:07:17.069+0000] {docker.py:73} INFO -     215         memory_profiler_cls,
[2024-12-24T18:07:17.069+0000] {docker.py:73} INFO -     216     )
[2024-12-24T18:07:17.070+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:17.070+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/context.py:436, in SparkContext._ensure_initialized(cls, instance, gateway, conf)
[2024-12-24T18:07:17.070+0000] {docker.py:73} INFO -     434 with SparkContext._lock:
[2024-12-24T18:07:17.070+0000] {docker.py:73} INFO -     435     if not SparkContext._gateway:
[2024-12-24T18:07:17.070+0000] {docker.py:73} INFO - --> 436         SparkContext._gateway = gateway or launch_gateway(conf)
[2024-12-24T18:07:17.070+0000] {docker.py:73} INFO -     437         SparkContext._jvm = SparkContext._gateway.jvm
[2024-12-24T18:07:17.070+0000] {docker.py:73} INFO -     439     if instance:
[2024-12-24T18:07:17.070+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:17.071+0000] {docker.py:73} INFO - File /opt/conda/lib/python3.11/site-packages/pyspark/java_gateway.py:107, in launch_gateway(conf, popen_kwargs)
[2024-12-24T18:07:17.071+0000] {docker.py:73} INFO -     104     time.sleep(0.1)
[2024-12-24T18:07:17.071+0000] {docker.py:73} INFO -     106 if not os.path.isfile(conn_info_file):
[2024-12-24T18:07:17.071+0000] {docker.py:73} INFO - --> 107     raise PySparkRuntimeError(
[2024-12-24T18:07:17.071+0000] {docker.py:73} INFO -     108         error_class="JAVA_GATEWAY_EXITED",
[2024-12-24T18:07:17.071+0000] {docker.py:73} INFO -     109         message_parameters={},
[2024-12-24T18:07:17.071+0000] {docker.py:73} INFO -     110     )
[2024-12-24T18:07:17.072+0000] {docker.py:73} INFO -     112 with open(conn_info_file, "rb") as info:
[2024-12-24T18:07:17.075+0000] {docker.py:73} INFO -     113     gateway_port = read_int(info)
[2024-12-24T18:07:17.075+0000] {docker.py:73} INFO - 
[2024-12-24T18:07:17.076+0000] {docker.py:73} INFO - PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-24T18:07:17.705+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-24T18:07:17.739+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_Calendar_NTBK, task_id=NB_Notebook_job, run_id=manual__2024-12-24T18:06:48.628500+00:00, execution_date=20241224T180648, start_date=20241224T180650, end_date=20241224T180717
[2024-12-24T18:07:17.798+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-24T18:07:17.802+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 477 for task NB_Notebook_job (Docker container failed: {'StatusCode': 1}; 659)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-12-24T18:07:17.852+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-24T18:07:17.941+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-24T18:07:17.945+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
